name="nicomado"

main="./app.ts"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-10-01"

[assets]
directory = "./build/client"

[build]
command = "npm run build"
